
<h2>Vista Index...</h2>
<?php if(isset($this->usuarios) && count($this->usuarios)):?>
<table>
    <?php for($i=0;$i<count($this->usuarios);$i++):?>
    <tr>
        <td><?php echo $this->usuarios[$i]['id'];?></td>
        <td><?php echo $this->usuarios[$i]['username'];?></td>
        <td><?php echo $this->usuarios[$i]['password'];?></td>
    </tr>
    <?php endfor;?>
</table>
<?php echo count($this->usuario);?>
<?php else: ?>
<p><strong>No hay usuarios</strong></p>
<?php endif; ?>

<pre>
<?php print_r($this->usuarios);?>
</pre>