<h2>Registro</h2>

<form name="form1" method="post" action="">

    <input type="hidden" value="1" name="enviar" />

    <p>
        <label for="nombre">Nombre</label>
        <input type="text" name="nombre" id="nombre" value="Pepe">
    </p>

    <p>
        <label for="usuario">Usuario</label>
        <input type="text" name="usuario" id="usuario" value="pepillo">
    </p>



    <p>
        <label for="email">email</label>
        <input type="text" name="email" id="email" value="pe@pi.llo">
    </p>

    <p>
        <label for="password">password</label>
        <input type="text" name="password" id="password" value="1234">
    </p>

    <p>
        <label for="confirmar">confirmar</label>
        <input type="text" name="confirmar" id="confirmar" value="1234">
    </p>

    <p>
        <input type="submit" value="enviar">
    </p>


</form>